server:
  servlet:
    context-path: /pp-event-control-center
spring:
  application:
    name: pp-event-control-center
  mvc:
    servlet:
      load-on-startup: 0
    static-path-pattern: /static/**
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl
    charset: UTF-8
    request-context-attribute: request
    settings.number_format: 0.##########
eros:
  football:
    app:
      id: 11927
      name: pp-event
management:
  health:
    mail:
      enabled: false
mybatis-plus:
  mapper-locations: classpath:/mybatis-mapper/*Mapper.xml
xxl:
  job:
    triggerpool:
      fast:
        max: 200
      slow:
        max: 100
    i18n: zh_CN
    logretentiondays: 30
    accessToken:
